 - name: Install NIFI
   hosts: all
   become: true

   tasks:
     - name: Creating Nifi
       file:
            path: /opt/nifi
            mode: 0775
            state: directory

     - name: Install nifi
       get_url:
               url: http://www-eu.apache.org/dist/nifi/1.3.0/nifi-1.3.0-bin.tar.gz
               dest: /opt/nifi
               mode: 0755
               owner: root
               group: root

     - name: extract
       unarchive:
                 src: /opt/nifi/nifi-1.3.0-bin.tar.gz
                 dest: /opt/nifi
                 copy: no


     - name: Copy the Nifi systemd service file
       template:
                src: etc/systemd/system/nifi.service.j2
                dest: /etc/systemd/system/nifi.service
                mode: 0644
                owner: root
                group: root
            
     - name: enable nifi service
       systemd:
               name: nifi.service
               state: started
               enabled: true
               daemon_reload: yes
