- name: Nifi installation
  hosts: linux_all
  become: true
  tasks:
    - name: Creating Nifi folder
      file:
            path: /opt/nifi
            state: directory
            mode: 0755
    - name: downloading and extracting nifi tarball
      unarchive:
            src: http://www-eu.apache.org/dist/nifi/1.3.0/nifi-1.3.0-bin.tar.gz
            dest: /opt/nifi
            remote_src: yes
