- name: zeppelin installation
  hosts: linux_all
  become: true
  tasks:
    - name: creating zeppelin folder
      file:
            path: /opt/zeppelin
            state: directory
            mode: 0755
    - name: downloading and extracting zeppelin tarball
      unarchive:
            src: http://www-eu.apache.org/dist/zeppelin/zeppelin-0.7.3/zeppelin-0.7.3-bin-all.tgz
            dest: /opt/zeppelin
            remote_src: yes
    - name: Copy the Zeppelin systemd service file
      template:
            src: zeppelin.service.j2
            dest: /etc/systemd/system/zeppelin.service
            mode: 0644
            owner: root
            group: root
